// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type overlayEbpfBridge struct {
	BridgeId uint32
	Veths    [2]uint32
}

type overlayEbpfNs struct {
	NsId  uint32
	Veths [1]uint32
}

type overlayEbpfVeth struct {
	VethId        uint32
	PairVethId    uint32
	BridgeId      uint32
	IpAddr        uint32
	HostInterface uint32
}

type overlayIpPortPair struct {
	NsId uint32
	Ip   uint32
	Port uint16
	_    [2]byte
}

type overlaySockaddrData struct {
	UaddrPtr int64
	Addrlen  int64
}

// loadOverlay returns the embedded CollectionSpec for overlay.
func loadOverlay() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OverlayBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load overlay: %w", err)
	}

	return spec, err
}

// loadOverlayObjects loads overlay and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*overlayObjects
//	*overlayPrograms
//	*overlayMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOverlayObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOverlay()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// overlaySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlaySpecs struct {
	overlayProgramSpecs
	overlayMapSpecs
	overlayVariableSpecs
}

// overlayProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayProgramSpecs struct {
	SockSetState          *ebpf.ProgramSpec `ebpf:"sock_set_state"`
	TpSysEnterBind        *ebpf.ProgramSpec `ebpf:"tp_sys_enter_bind"`
	TpSysEnterConnect     *ebpf.ProgramSpec `ebpf:"tp_sys_enter_connect"`
	TpSysEnterGetsockname *ebpf.ProgramSpec `ebpf:"tp_sys_enter_getsockname"`
	TpSysExitGetsockname  *ebpf.ProgramSpec `ebpf:"tp_sys_exit_getsockname"`
}

// overlayMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayMapSpecs struct {
	EbpfBridgeMap *ebpf.MapSpec `ebpf:"ebpf_bridge_map"`
	EbpfNsMap     *ebpf.MapSpec `ebpf:"ebpf_ns_map"`
	EbpfVethMap   *ebpf.MapSpec `ebpf:"ebpf_veth_map"`
	FdSockMap     *ebpf.MapSpec `ebpf:"fd_sock_map"`
	HostToNsMap   *ebpf.MapSpec `ebpf:"host_to_ns_map"`
	NsToHostMap   *ebpf.MapSpec `ebpf:"ns_to_host_map"`
	PidEnidMap    *ebpf.MapSpec `ebpf:"pid_enid_map"`
}

// overlayVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type overlayVariableSpecs struct {
}

// overlayObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayObjects struct {
	overlayPrograms
	overlayMaps
	overlayVariables
}

func (o *overlayObjects) Close() error {
	return _OverlayClose(
		&o.overlayPrograms,
		&o.overlayMaps,
	)
}

// overlayMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayMaps struct {
	EbpfBridgeMap *ebpf.Map `ebpf:"ebpf_bridge_map"`
	EbpfNsMap     *ebpf.Map `ebpf:"ebpf_ns_map"`
	EbpfVethMap   *ebpf.Map `ebpf:"ebpf_veth_map"`
	FdSockMap     *ebpf.Map `ebpf:"fd_sock_map"`
	HostToNsMap   *ebpf.Map `ebpf:"host_to_ns_map"`
	NsToHostMap   *ebpf.Map `ebpf:"ns_to_host_map"`
	PidEnidMap    *ebpf.Map `ebpf:"pid_enid_map"`
}

func (m *overlayMaps) Close() error {
	return _OverlayClose(
		m.EbpfBridgeMap,
		m.EbpfNsMap,
		m.EbpfVethMap,
		m.FdSockMap,
		m.HostToNsMap,
		m.NsToHostMap,
		m.PidEnidMap,
	)
}

// overlayVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayVariables struct {
}

// overlayPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOverlayObjects or ebpf.CollectionSpec.LoadAndAssign.
type overlayPrograms struct {
	SockSetState          *ebpf.Program `ebpf:"sock_set_state"`
	TpSysEnterBind        *ebpf.Program `ebpf:"tp_sys_enter_bind"`
	TpSysEnterConnect     *ebpf.Program `ebpf:"tp_sys_enter_connect"`
	TpSysEnterGetsockname *ebpf.Program `ebpf:"tp_sys_enter_getsockname"`
	TpSysExitGetsockname  *ebpf.Program `ebpf:"tp_sys_exit_getsockname"`
}

func (p *overlayPrograms) Close() error {
	return _OverlayClose(
		p.SockSetState,
		p.TpSysEnterBind,
		p.TpSysEnterConnect,
		p.TpSysEnterGetsockname,
		p.TpSysExitGetsockname,
	)
}

func _OverlayClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed overlay_bpfel.o
var _OverlayBytes []byte
